import OysterMushroomsImage from "@/public/images/product4.jpg";
import OysterMushroomsImagePack from "@/public/images/product7.jpg";
import OysterMushroomsImagePowder from "@/public/images/powder.jpg";
import freshMushroomsImage from "@/public/images/product1.jpg";
import DriedMushroomsImage from "@/public/images/product2.jpg";
import MushroomSoupPowderImage from "@/public/images/product10.jpg";
import PortobelloMushroomsImage from "@/public/images/product13.jpg";
import ChanterelleMushroomsImage from "@/public/images/product16.jpg";
import TruffleMushroomsImage from "@/public/images/product17.jpg";
import ShiimejiMushroomsImage from "@/public/images/product19.jpg";
import MushroomGrowingKitImage from "@/public/images/product18.jpg";
import MushroomSporesImage from "@/public/images/product14.jpg";
import OysterMushroomsImagePowderr from "@/public/images/product1.jpg";
const oysterMushroomPricePerKg = 5000;
const oysterMushroomPricePer250gPack = 2000;
const oysterPowderSpawnPrice = 1000;
export const productData = [
  {
    _id: 1,
    title: "Oyster Mushrooms",
    isNew: true,
    oldPrice: "6500",
    price: oysterMushroomPricePerKg,
    description: "Fresh Oyster Mushroom for a unique flavor.",
    category: "fresh",
    image: OysterMushroomsImage,
    rating: 4,
    quantity: 2,
  },
  {
    _id: 2,
    title: "Oyster Mushrooms Pack",
    isNew: true,
    oldPrice: "3500",
    price: oysterMushroomPricePer250gPack,
    description: "Premium Oyster Mushroom 250g packages with unique flavours.",
    category: "fresh",
    image: OysterMushroomsImagePack,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 3,
    title: "Oyester Powder Spawn",
    isNew: true,
    oldPrice: 2000,
    price: oysterPowderSpawnPrice,
    description: "Oyester Powder Spawn",
    category: "dried",
    image: OysterMushroomsImagePowder,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 4,
    title: "Fresh Mushrooms",
    isNew: true,
    oldPrice: "2000",
    price: 1500,
    description: "Fresh mushrooms for your recipes.",
    category: "fresh",
    image: freshMushroomsImage,
    rating: 4,
    quantity: 1,
  },
  {
    _id: 5,
    title: "Dried Mushrooms",
    isNew: true,
    oldPrice: "7000",
    price: 6500,
    description: "Premium dried mushrooms for long-lasting use.",
    category: "dried",
    image: DriedMushroomsImage,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 6,
    title: "Mushroom Soup Powder",
    isNew: true,
    oldPrice: "6500",
    price: 5599,
    description: "Convenient mushroom soup powder.",
    category: "powder",
    image: MushroomSoupPowderImage,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 7,
    title: "Portobello Mushrooms",
    isNew: false,
    oldPrice: "2000",
    price: 1800,
    description: "Large and meaty Portobello mushrooms.",
    category: "fresh",
    image: PortobelloMushroomsImage,
    rating: 4,
    quantity: 1,
  },
  {
    _id: 8,
    title: "Chanterelle Mushrooms",
    isNew: false,
    oldPrice: "5000",
    price: 3500,
    description: "Golden and delicate Chanterelle mushrooms.",
    category: "fresh",
    image: ChanterelleMushroomsImage,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 9,
    title: "Truffle Mushrooms",
    isNew: false,
    oldPrice: "3500",
    price: 2450,
    description: "Luxurious and aromatic Truffle mushrooms.",
    category: "fresh",
    image: TruffleMushroomsImage,
    rating: 5,
    quantity: 1,
  },
  {
    _id: 10,
    title: "Shimeji Mushrooms",
    isNew: false,
    oldPrice: "2000",
    price: 1400,
    description: "Nutty and flavorful Shimeji mushrooms.",
    category: "fresh",
    image: ShiimejiMushroomsImage,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 11,
    title: "Shiimeji Mushrooms",
    isNew: false,
    oldPrice: "1300",
    price: 1200,
    description: "Tiny but flavorful Shiimeji mushrooms.",
    category: "fresh",
    image: ShiimejiMushroomsImage,
    rating: 4,
    quantity: 1,
  },
  {
    _id: 12,
    title: "Mushroom Growing Kit",
    isNew: false,
    oldPrice: "8000",
    price: 6500,
    description: "Start your mushroom cultivation journey with this kit.",
    category: "kit",
    image: MushroomGrowingKitImage,
    rating: 2,
    quantity: 1,
  },
  {
    _id: 13,
    title: "Mushroom Spores",
    isNew: false,
    oldPrice: "1200",
    price: 1000,
    description: "High-quality mushroom spores for advanced growers.",
    category: "spores",
    image: MushroomSporesImage,
    rating: 4,
    quantity: 1,
  },
  {
    _id: 14,
    title: "Oyster Mushrooms",
    isNew: true,
    oldPrice: "6500",
    price: oysterMushroomPricePerKg,
    description: "Fresh Oyster Mushroom for a unique flavor.",
    category: "fresh",
    image: OysterMushroomsImage,
    rating: 4,
    quantity: 2,
  },
  {
    _id: 15,
    title: "Oyster Mushrooms Pack",
    isNew: true,
    oldPrice: "3500",
    price: oysterMushroomPricePer250gPack,
    description: "Premium Oyster Mushroom 250g packages with unique flavours.",
    category: "fresh",
    image: OysterMushroomsImagePack,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 16,
    title: "Oyester Powder Spawn",
    isNew: true,
    oldPrice: 2000,
    price: oysterPowderSpawnPrice,
    description: "Oyester Powder Spawn",
    category: "dried",
    image: OysterMushroomsImagePowderr,
    rating: 3,
    quantity: 1,
  },
];
export const trendingProducts = [
  {
    _id: 1,
    title: "Oyster Mushrooms",
    isNew: true,
    oldPrice: "6500",
    price: oysterMushroomPricePerKg,
    description: "Fresh Oyster Mushroom for a unique flavor.",
    category: "fresh",
    image: OysterMushroomsImage,
    rating: 4,
    quantity: 2,
  },
  {
    _id: 2,
    title: "Oyster Mushrooms Pack",
    isNew: true,
    oldPrice: "3500",
    price: oysterMushroomPricePer250gPack,
    description: "Premium Oyster Mushroom 250g packages with unique flavours.",
    category: "fresh",
    image: OysterMushroomsImagePack,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 3,
    title: "Oyester Powder Spawn",
    isNew: true,
    oldPrice: 2000,
    price: oysterPowderSpawnPrice,
    description: "Oyester Powder Spawn",
    category: "dried",
    image: OysterMushroomsImagePowder,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 4,
    title: "Fresh Mushrooms",
    isNew: true,
    oldPrice: "2000",
    price: 1500,
    description: "Fresh mushrooms for your recipes.",
    category: "fresh",
    image: freshMushroomsImage,
    rating: 4,
    quantity: 1,
  },
  {
    _id: 5,
    title: "Dried Mushrooms",
    isNew: true,
    oldPrice: "7000",
    price: 6500,
    description: "Premium dried mushrooms for long-lasting use.",
    category: "dried",
    image: DriedMushroomsImage,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 6,
    title: "Mushroom Soup Powder",
    isNew: true,
    oldPrice: "6500",
    price: 5599,
    description: "Convenient mushroom soup powder.",
    category: "powder",
    image: MushroomSoupPowderImage,
    rating: 3,
    quantity: 1,
  },
  {
    _id: 7,
    title: "Portobello Mushrooms",
    isNew: false,
    oldPrice: "2000",
    price: 1800,
    description: "Large and meaty Portobello mushrooms.",
    category: "fresh",
    image: PortobelloMushroomsImage,
    rating: 4,
    quantity: 1,
  },
];
